language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  script: "npm build"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
      - luchyx@gmail.com
    on_success: change
    on_failure: always
