version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            mkdir /tmp/artifacts;
            echo "my artifact file" > /tmp/artifacts/artifact-1;
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run-script build
      - store_artifacts:
          path: /tmp/artifacts
          destination: artifact-file
workflows:
  build-and-test:
    jobs:
      - build-and-test
